from manim import *
import numpy as np

class ManimStart(MovingCameraScene):
    def construct(self):

        #开头：展示菲涅尔积分
        t1 = Text("菲涅尔积分" , color=BLUE).to_edge(UP)
        self.play(Write(t1))
        t2 = MathTex(r"\int_0^{\infty}\sin\left(x^2\right)dx").shift(LEFT * 2).shift(UP * 1)
        t3 = MathTex(r"\int_0^{\infty}\cos \left(x^2\right)dx").shift(RIGHT * 2).shift(UP * 1)
        self.play(Write(t2) , Write(t3))
        self.wait(4)
        t4 = Text("遇到这两个不定积分").to_edge(DOWN)
        self.play(Write(t4))
        self.wait(2)
        t5 = Text('"常规"的方法是做不出来的').to_edge(DOWN)
        self.play(ReplacementTransform(t4 , t5))
        self.wait(2)
        t6 = Text('因为被积式都没有初等原函数').to_edge(DOWN)
        self.play(ReplacementTransform(t5 , t6))
        self.wait(2)
        t7 = Text('这里我会带来运用伽马函数来求解这两道积分').to_edge(DOWN)
        self.play(ReplacementTransform(t6 , t7))
        self.wait(3)
        self.play(FadeOut(*self.mobjects))
        self.wait(1)

        #求解过程
        t1 = Text("我们很容易考虑到这个积分").to_edge(DOWN)
        self.play(Write(t1))
        l1 = MathTex(r"I=\int_{0}^{\infty}e^{ix^{2}}dx")
        self.play(Write(l1))
        self.wait(2)
        t2 = Text("因为根据欧拉公式恒等变换后可以发现").to_edge(DOWN)
        self.play(ReplacementTransform(t1 , t2))
        self.wait(1)
        self.play(l1.animate.shift(LEFT * 4.2))
        l2 = MathTex(r"=\int_0^{\infty}\cos \left(x^2\right)dx+i\int_0^{\infty}\sin \left(x^2\right)dx").next_to(l1 , RIGHT , buff=0.3)
        self.play(Write(l2))
        self.wait(6)
        t3 = Text("解出这个新积分再分离实虚部").to_edge(DOWN)
        self.play(ReplacementTransform(t2 , t3))
        self.wait(2)
        t4 = Text("就是我们要求的目标积分的结果").to_edge(DOWN)
        self.play(ReplacementTransform(t3 , t4))
        self.wait(2)
        t5 = Text("我们就对它入手").to_edge(DOWN)
        self.play(ReplacementTransform(t4 , t5))
        self.play(FadeOut(l2))
        self.play(l1.animate.shift(RIGHT * 4.2))
        t6 = Text("先对原积分换元").to_edge(DOWN)
        self.play(ReplacementTransform(t5 , t6))
        self.wait(1)
        self.play(l1.animate.shift(UP * 1))
        l2 = MathTex(r"x^{2}=t,x=\sqrt{t},dx=\frac{dt}{2\sqrt{t}}").next_to(l1 , DOWN)
        self.play(Write(l2))
        self.wait(1)
        self.play(l1.animate.shift(LEFT * 2.3))
        l3 = MathTex(r"=\frac{1}{2}\int_{0}^{\infty}t^{-1/2}e^{it}dt").next_to(l1 , RIGHT , buff=0.3)
        self.play(Write(l3))
        self.wait(2)
        t7 = Text("这已经有伽马函数的样子了").to_edge(DOWN)
        self.play(ReplacementTransform(t6 , t7))
        self.wait(2)
        t8 = Text("我这直接给出这个推广公式").to_edge(DOWN)
        self.play(ReplacementTransform(t7 , t8))
        self.wait(2)
        self.play(FadeOut(l2))
        l4 = MathTex(r"\int_{0}^{\infty}t^{z-1}e^{-at}dt=\frac{\Gamma(z)}{a^{z}}").next_to(l1 , DOWN)
        l5 = MathTex(r"\Re(z),\Re(a)>0").next_to(l4 , RIGHT , buff= 1)
        self.play(Write(l4) , Write(l5))
        VG = VGroup(l4 , l5)
        gold_border = SurroundingRectangle(
            VG,
            color=GOLD,
            buff=0.15,          
            stroke_width=6      
        )
        self.play(Create(gold_border))
        self.play(FadeOut(gold_border))
        self.wait(1)
        t9 = Text("（读者可自推公式和收敛条件）").to_edge(DOWN)
        self.play(ReplacementTransform(t8 , t9))
        self.wait(2)
        t10 = Text("可是I的被积式与之对应公式中的a").to_edge(DOWN)
        self.play(ReplacementTransform(t9 , t10))
        self.wait(2)
        t11 = Text("不满足实部大于零").to_edge(DOWN)
        self.play(ReplacementTransform(t10 , t11))
        self.wait(2)
        t12 = Text("怎么办？").to_edge(DOWN)
        self.play(ReplacementTransform(t11 , t12))
        self.wait(2)
        l6 = MathTex(r"I=\frac{1}{2}\int_{0}^{\infty}t^{-1/2}e^{it}dt").to_edge(UP)
        VG = VGroup(l1 , l3)
        VG2 = VGroup(l4 , l5)
        self.play(ReplacementTransform(VG , l6) , VG2.animate.shift(UP * 2))
        t13 = Text("根据狄利克雷判别法I是条件收敛的").to_edge(DOWN)
        self.play(ReplacementTransform(t12 , t13))
        self.wait(2)
        t14 = Text("那就引极限呗（右极限）").to_edge(DOWN)
        self.play(ReplacementTransform(t13 , t14))
        self.wait(2)
        l7 = MathTex(r"I_{\epsilon} &= \frac{1}{2} \int_{0}^{\infty}t^{-1/2}e^{-(\epsilon-i)t}dt = \frac{\Gamma(\frac{1}{2})}{2(\epsilon-i)^{\frac{1}{2}}} \\ \lim_{\epsilon \to 0^{+}} I_{\epsilon} &= \lim_{\epsilon \to 0^{+}} \frac{\sqrt{\pi}}{2\sqrt{\epsilon-i}} \Rightarrow I=\frac{\sqrt{\pi}}{2\sqrt{i}}=\frac{\sqrt{\pi}}{2}e^{i\pi/4}").next_to(VG2 , DOWN)
        self.play(Write(l7))
        self.wait(7)
        t15 = Text("分离实虚部，即可求得结果（处理虚数时取主部）").to_edge(DOWN)
        self.play(ReplacementTransform(t14 , t15))
        self.wait(2)
        self.play(FadeOut(*self.mobjects))
        
        #展示最后结果
        l1 = MathTex(r"\int_{0}^{\infty}\sin(x^{2})dx=\int_{0}^{\infty}\cos(x^{2})dx=\sqrt{\frac{\pi}{8}}")
        self.play(Write(l1))
        gold_border = SurroundingRectangle(
            l1,
            color=GOLD,
            buff=0.15,          
            stroke_width=6      
        )
        self.play(Create(gold_border))
        self.wait(4)